CI : Matrix Docker, install cmake recent version for debian stable

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,8 +6,8 @@ jobs:
   # Runner
 
   Runner-ubuntu-20_04:
-    name: Runner-Ubuntu-20.04
-    runs-on: Ubuntu-20.04
+    name: Runner-ubuntu-20.04
+    runs-on: ubuntu-20.04
     strategy:
       fail-fast: false
     env:
@@ -32,7 +32,7 @@ jobs:
           ctest
 
   Runner-windows-2019:
-    name: Runner-Windows-2019
+    name: Runner-windows-2019
     runs-on: windows-2019
     strategy:
       fail-fast: false
@@ -183,17 +183,36 @@ jobs:
       fail-fast: false
       matrix:
         os: ['debian:stable', 'debian:testing', 'debian:unstable']
+        include:
+          - os: 'debian:stable'
+            custom_variable: 'Custom variable for Debian Stable'
+          - os: 'debian:testing'
+            custom_variable: 'Custom variable for Debian Testing'
+          - os: 'debian:unstable'
+            custom_variable: 'Custom variable for Debian Unstable'
     env:
       CMAKE_SOURCE_DIR: /__w/cmaketutorial/cmaketutorial
       CMAKE_BUILD_DIR: /__w/cmaketutorial/cmaketutorial/builddir
     steps:
       - name: Check out repository code
         uses: actions/checkout@v2
+      - name: Print custom variable
+        shell: bash
+        run : echo "matrix.custom_variable = ${{ matrix.custom_variable }}"
       - name: Install prerequisites
+        shell: bash
         run: |
           apt-get update
           apt-get upgrade -y
-          DEBIAN_FRONTEND="noninteractive" apt-get install -y build-essential cmake
+          if [ "${{ matrix.os }}" != "debian:stable" ]; then
+            DEBIAN_FRONTEND="noninteractive" apt-get install -y build-essential cmake
+          else
+            DEBIAN_FRONTEND="noninteractive" apt-get install -y build-essential wget
+            checksum="bf496ce869d0aa8c1f57e4d1a2e50c8f2fb12a6cd7ccb37ad743bb88f6b76a1e"
+            wget -O /tmp/cmake.tar.gz https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-x86_64.tar.gz
+            if [ `sha256sum /tmp/cmake.tar.gz  | awk '{ print $1}'` != "${checksum}" ]; then echo "/tmp/cmake.tar.gz checksum error"; exit 1; fi
+            tar xf /tmp/cmake.tar.gz -C /usr/local --strip-components 1
+          fi
       - name: Configure
         shell: bash
         run: |
